### ISSUE TITLE
RFC - Rename HallwayTracks

### ISSUE THREAD

**Issue by ChaelCodes** [ChaelCodes/HallwayTracks#181]
This is a Request for Comments(RFC) for renaming HallwayTracks. Normally an RFC proposes a change and requests comments, but in this case, I would really like your recommendations for a new name.

hallwaytrack.io has come out of dormancy, and especially since the releases would be close together, I'd like to avoid HallwayTracks as a name.
This has previously happened with ConfBuddies, and ConfBuddy.io which I discovered after development started.

The new name should:
- clearly convey the concept: meeting your friends at a conference/event
- Be singular - I don't want this pluralization of an app.io to happen again
- Be short
- Have no legal infringement - No "Where's Waldo?"

Preferences:
- Domains that are not international - I don't want to use another country's domains

**Comment by ChaelCodes** [comment]
All name suggestions will be copied here for easier reading.

- HallwayTrax (@ChaelCodes)
   - Still slightly confusing when said aloud, hard to remember
- ~~Where's Waldo?~~
   - Potential legal issues here, sorry. Also, we've lost the event concept.

**Comment by Caleb-T-Owens** [comment]
- HoozAtConf.com
- RFCForNewName.com

**Comment by ChaelCodes** [comment]
I'm really liking See You At, especially because there are so many options for domains.

.com, .dev, .io, .app, .conf (but it's expensive)
.events/.event is available

Do you think I could get away with CU@ as a logo?

**Comment by exegeteio** [comment]
- MarcoConfo.com

**Comment by anakimluke** [comment]
Here are a few suggestions:

* RendezHub
* RandezSite
* ConfTag
* ConfMagnet

'Rendez' as short for 'rendezvous'.

I couldn't find any app/site that conflicts with those, although I found a 'Magnet Events' site that sounds similar to the ConfMagnet suggestion. I'm not sure if it's _too_ similar.

**Comment by ChaelCodes** [comment]
A name has been selected - thank you to Twitch chat and AVN8TR for the suggestion - Untitled Friendship App!!!
